import {defineField, defineType} from 'sanity'
import {icons} from '@sanity/icons'
import {altTextField} from '../fields/altText'

export const siteSettings = defineType({
	name: 'siteSettings',
	title: 'Site settings',
	type: 'document',
	icon: icons.cog,
	description: 'Global brand, navigation, footer, and business-contact content shared across every page.',
	groups: [
		{name: 'brand', title: 'Brand & navigation'},
		{name: 'footer', title: 'Footer'},
		{name: 'contact', title: 'Business contact'},
		{name: 'seo', title: 'Default SEO'},
	],
	fields: [
		defineField({
			name: 'brandName',
			title: 'Brand name',
			type: 'string',
			group: 'brand',
			validation: (rule) => rule.required(),
		}),
		defineField({
			name: 'brandTagline',
			title: 'Brand tagline',
			type: 'string',
			group: 'brand',
		}),
		defineField({
			name: 'logo',
			title: 'Logo',
			type: 'image',
			fields: [altTextField],
			group: 'brand',
		}),
		defineField({
			name: 'bookNowLabel',
			title: '"Book now" nav CTA label',
			type: 'string',
			group: 'brand',
			initialValue: 'Book now',
		}),
		defineField({
			name: 'navLinks',
			title: 'Navigation links',
			description: 'Main nav items, in display order. The site can gain or lose links here without a code change.',
			type: 'array',
			of: [{type: 'navLink'}],
			group: 'brand',
			validation: (rule) => rule.min(1),
		}),
		defineField({
			name: 'footerBrandDescription',
			title: 'Footer brand description',
			type: 'text',
			rows: 2,
			group: 'footer',
		}),
		defineField({
			name: 'footerLogos',
			title: 'Footer credential logos',
			type: 'array',
			of: [{type: 'credentialBadge'}],
			group: 'footer',
		}),
		defineField({
			name: 'footerNavLinks',
			title: 'Footer "Navigate" column',
			description: 'Page links for the footer "Navigate" column, e.g. Services (/services), Gallery (/gallery).',
			type: 'array',
			of: [{type: 'navLink'}],
			group: 'footer',
		}),
		defineField({
			name: 'connectLinks',
			title: 'Footer "Connect" column',
			description:
				'Contact links for the footer "Connect" column, e.g. email (mailto:…), phone (tel:+1…) and Instagram.',
			type: 'array',
			of: [{type: 'contactLink'}],
			group: 'footer',
		}),
		defineField({
			name: 'footerHours',
			title: 'Footer "Hours" column',
			type: 'array',
			of: [{type: 'hoursLine'}],
			group: 'footer',
		}),
		defineField({
			name: 'copyrightText',
			title: 'Copyright text',
			description: 'e.g. "© 2026 Curated Organization. All rights reserved."',
			type: 'string',
			group: 'footer',
		}),
		defineField({
			name: 'credentialBadges',
			title: 'About-page credential badges',
			description: 'Reused certification/membership logos shown on the Services "About" section.',
			type: 'array',
			of: [{type: 'credentialBadge'}],
			group: 'brand',
		}),
		defineField({
			name: 'businessPhoneDisplay',
			title: 'Business phone (display)',
			description: 'e.g. "(703) 555-0182"',
			type: 'string',
			group: 'contact',
		}),
		defineField({
			name: 'businessPhoneTel',
			title: 'Business phone (tel: link)',
			description: 'e.g. "+17035550182"',
			type: 'string',
			group: 'contact',
		}),
		defineField({
			name: 'businessHours',
			title: 'Business hours (booking call info)',
			description: 'e.g. "Mon-Fri, 9am-5pm ET · Sat by appointment"',
			type: 'string',
			group: 'contact',
		}),
		defineField({
			name: 'defaultSeo',
			title: 'Default SEO (site-wide fallback)',
			type: 'seo',
			group: 'seo',
		}),
	],
	preview: {
		prepare: () => ({title: 'Site settings'}),
	},
})
